import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for Xelera.ai.",
};

export default function TermsPage() {
  return (
    <div className="section-shell pt-24">
      <div className="mx-auto max-w-4xl">
        <h1 className="text-4xl font-semibold tracking-[-0.05em] text-slate-950">Terms of Service</h1>
        <p className="mt-3 text-slate-500">Last Updated: December 15, 2025</p>

        <div className="mt-10 space-y-8 text-base leading-8 text-slate-700">
          <section>
            <p>
              These Terms of Service govern your access to and use of the Xelera.ai website and any
              services, consulting engagements, prototypes, automations, or AI systems delivered by
              Xelera.ai.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-950">1. Scope of Services</h2>
            <p className="mt-3">
              Xelera provides AI consulting, workflow automation, software prototypes, agentic
              systems, and related business technology services. Specific deliverables, timelines,
              and responsibilities are defined in proposals, statements of work, or written
              agreements.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-950">2. Eligibility and Acceptable Use</h2>
            <p className="mt-3">
              You agree to use the website and services only for lawful business purposes and in a
              manner that does not infringe the rights of others or misuse the systems, prototypes,
              or outputs generated by Xelera.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-950">3. Client Responsibilities</h2>
            <p className="mt-3">
              Clients are responsible for providing accurate information, securing internal
              approvals, and ensuring that any data shared with Xelera can be lawfully used for the
              agreed engagement.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-950">4. AI-Generated Outputs</h2>
            <h3 className="mt-4 text-xl font-medium text-slate-950">4.1 Probabilistic Nature</h3>
            <p className="mt-2">
              AI-generated outputs may be inaccurate, incomplete, or outdated. Outputs should be
              reviewed by humans before production or business use.
            </p>
            <h3 className="mt-4 text-xl font-medium text-slate-950">4.2 No Legal, Medical, or Financial Advice</h3>
            <p className="mt-2">
              AI outputs are not legal, medical, or financial advice. You are responsible for
              obtaining professional advice when required.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-950">5. Intellectual Property</h2>
            <h3 className="mt-4 text-xl font-medium text-slate-950">5.1 Xelera IP</h3>
            <p className="mt-2">
              All pre-existing intellectual property, frameworks, methodologies, templates, code
              libraries, and tools used by Xelera remain the exclusive property of Xelera.ai.
            </p>
            <h3 className="mt-4 text-xl font-medium text-slate-950">5.2 Client Deliverables</h3>
            <p className="mt-2">Unless otherwise agreed in writing:</p>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>Custom deliverables created specifically for a client may be licensed or assigned based on the contract.</li>
              <li>Xelera retains the right to reuse non-client-specific learnings, patterns, and anonymized insights.</li>
            </ul>
            <h3 className="mt-4 text-xl font-medium text-slate-950">5.3 Website Content</h3>
            <p className="mt-2">
              All website content, including text, visuals, branding, and logos, is owned by Xelera
              and may not be copied without written permission.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-950">6. Confidentiality</h2>
            <p className="mt-3">
              Both parties agree to protect confidential information shared during engagements.
              Confidential information does not include information that is publicly available,
              independently developed, or lawfully received from a third party. Confidentiality
              obligations survive termination of Services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-950">7. Data Privacy &amp; Security</h2>
            <p className="mt-3">Our handling of personal data is governed by our Privacy Policy.</p>
            <p className="mt-3">Clients acknowledge that:</p>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>AI systems may process data to generate outputs.</li>
              <li>Clients are responsible for compliance with data protection laws applicable to their business.</li>
              <li>Sensitive or regulated data should not be shared unless explicitly agreed.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-950">8. Payment &amp; Fees</h2>
            <h3 className="mt-4 text-xl font-medium text-slate-950">8.1 Pricing</h3>
            <p className="mt-2">Fees are defined in written agreements, proposals, or statements of work.</p>
            <h3 className="mt-4 text-xl font-medium text-slate-950">8.2 No Refunds</h3>
            <p className="mt-2">Payments are non-refundable unless explicitly agreed in writing.</p>
            <h3 className="mt-4 text-xl font-medium text-slate-950">8.3 Late Payments</h3>
            <p className="mt-2">Late payments may result in suspension or termination of Services.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-950">9. Termination</h2>
            <p className="mt-3">Either party may terminate Services as defined in the applicable contract or immediately for material breach.</p>
            <p className="mt-3">Upon termination:</p>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>Access to Services may be revoked.</li>
              <li>Outstanding payments remain due.</li>
              <li>Confidentiality and IP clauses survive termination.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-950">10. Disclaimers</h2>
            <p className="mt-3 font-medium">THE SERVICES ARE PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE.&quot;</p>
            <p className="mt-3 font-medium">XELERA DISCLAIMS ALL WARRANTIES, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ACCURACY OR RELIABILITY OF AI OUTPUTS.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-950">11. Limitation of Liability</h2>
            <p className="mt-3">
              To the maximum extent permitted by law, Xelera shall not be liable for indirect,
              incidental, special, or consequential damages, and Xelera&apos;s total liability shall
              not exceed the amount paid by the client in the preceding 3 months.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-950">12. Indemnification</h2>
            <p className="mt-3">You agree to indemnify and hold harmless Xelera from claims arising out of your misuse of the Services, violation of laws or third-party rights, or data provided by you.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-950">13. Compliance &amp; Ethical Use</h2>
            <p className="mt-3">You agree not to use the Services to violate laws or regulations, infringe intellectual property, conduct surveillance or unethical profiling, or generate harmful or misleading content.</p>
            <p className="mt-3">Xelera reserves the right to refuse or terminate Services for unethical use.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-950">14. Governing Law</h2>
            <p className="mt-3">These Terms shall be governed by and construed in accordance with the local laws, without regard to conflict of law principles.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-950">15. Changes to Terms</h2>
            <p className="mt-3">We may update these Terms from time to time. Continued use of the Services after changes constitutes acceptance of the updated Terms.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-950">16. Contact Information</h2>
            <p className="mt-3">For questions regarding these Terms, please contact:</p>
            <div className="mt-4">
              <p className="font-medium text-slate-950">Xelera.ai</p>
              <p>Email: <a href="mailto:legal@xelera.ai" className="text-[var(--color-accent-strong)] hover:underline">legal@xelera.ai</a></p>
              <p>Website: <a href="https://www.xelera.ai" target="_blank" rel="noreferrer" className="text-[var(--color-accent-strong)] hover:underline">https://www.xelera.ai</a></p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
